package com.json.work.model;

public interface JSONData {
	
	public static String GET_JSON_Array ="[\r\n"
			+ "  {\r\n"
			+ "    \"name\": \"asdf222\",\r\n"
			+ "    \"age\": 25,\r\n"
			+ "    \"gender\": \"male\",\r\n"
			+ "    \"qualification\": \"BCA\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"line\": \"3rd line\",\r\n"
			+ "      \"locality\": \"RR Nagar\",\r\n"
			+ "      \"landMark\": \"Near Masal chowk\",\r\n"
			+ "      \"pinCode\": 560098\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"name\": \"asdf444\",\r\n"
			+ "    \"age\": 25,\r\n"
			+ "    \"gender\": \"male\",\r\n"
			+ "    \"qualification\": \"BCA\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"line\": \"3rd line\",\r\n"
			+ "      \"locality\": \"RR Nagar\",\r\n"
			+ "      \"landMark\": \"Near Masal chowk\",\r\n"
			+ "      \"pinCode\": 560098\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"name\": \"asdf3333\",\r\n"
			+ "    \"age\": 25,\r\n"
			+ "    \"gender\": \"male\",\r\n"
			+ "    \"qualification\": \"BCA\",\r\n"
			+ "    \"address\": {\r\n"
			+ "      \"line\": \"3rd line\",\r\n"
			+ "      \"locality\": \"RR Nagar\",\r\n"
			+ "      \"landMark\": \"Near Masal chowk\",\r\n"
			+ "      \"pinCode\": 560098\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "]";
	
	public static String GET_JSON="{\r\n"
			+ "  \"name\": \"asdf\",\r\n"
			+ "  \"age\": 25,\r\n"
			+ "  \"gender\": \"male\",\r\n"
			+ "  \"qualification\": \"BCA\",\r\n"
			+ "  \"address\": {\r\n"
			+ "    \"line\": \"3rd line\",\r\n"
			+ "    \"locality\": \"RR Nagar\",\r\n"
			+ "    \"landMark\": \"Near Masal chowk\",\r\n"
			+ "    \"pinCode\": 560098\r\n"
			+ "  }\r\n"
			+ "}";

}
